### ISSUE TITLE
Python cfn-response module

### ISSUE THREAD

**Issue by rawalpurvi** [udacity/FSND-Deploy-Flask-App-to-Kubernetes-Using-EKS#31]
When trying to create a stack on AWS using this yml file, I am getting the following error and causes the Stack creation to fail:

`Custom Resource failed to stabilize in expected time. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated  version.`

**Comment by SudKul** [comment]
Hi @rawalpurvi 
This issue has already been discussed in the [Knowledge hub](https://knowledge.udacity.com/?nanodegree=__pseudo_nd__any&page=1&project=619&query=Custom%20Resource%20failed%20to%20stabilize%20in%20expected%20time.%20&sort=RELEVANCE). The resolution includes updating the template file, in this [line of code](https://github.com/udacity/FSND-Deploy-Flask-App-to-Kubernetes-Using-EKS/blob/e73992d0475ab7583ace452eabc8855d209d1f94/ci-cd-codepipeline.cfn.yml#L159). We have recently updated the template file in the Udacity repository. 

If the problem persists, we would request you to raise a Knowledge thread with a few more details, such as:
1. What is your OS and terminal?
2. Classroom page link?
3. Command that is causing the error?
4. Provide a link to your Github repos, containing the template file.

Happy Learning
Udacity
