### ISSUE TITLE
Using aws/codebuild/docker:17.09.0 image breaks when pytest is implemented

### ISSUE THREAD

**Issue by nkatwesigye** [udacity/FSND-Deploy-Flask-App-to-Kubernetes-Using-EKS#7]
I see  missing module errors : for module typing & MatMult Module

**Comment by InfinityByTen** [comment]
The file /home/aseemdua/FullStack/FSND-Deployment/ci-cd-codepipeline.cfn.yml needs to change the base docker image to something like Ubuntu Standard or Amazon Linux 3 stanadard.

**Comment by SudKul** [comment]
Hi @nkatwesigye  
Though we are a little late to respond, it's worth mentioning for future readers to raise a [Knowledge thread](https://knowledge.udacity.com/) in such a case with a few more details, such as:

- What are your OS and terminal?
- Classroom page link?
- Command that is causing the error?
- Provide a link to your Github repos, containing the template file.

Happy Learning
Udacity
